# Docker compose (for local testing; when deploying, configure the container to use external MongoDB)
version: "3"
services:
    api:
        build:
            context: ./
            dockerfile: ./Dockerfile
        environment:
            - MONGODB_URL=mongodb://mongo:27017
        tty: true
        stdin_open: true
        ports:
            - 8088:8088
        volumes:
            - ./:/app # Development
            - /app/node_modules
        links:
            - mongo
        entrypoint: /bin/bash
    mongo:
        image: mongo:4.0.0
        tty: true
        privileged: true
        stdin_open: true